name: Release
on:
  push:
    tags:
      - test-v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Update homebrew tap
        run: gh workflow run update-formula.yml -f version=v2.8.3 -R ll-nick/homebrew-leadr
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_LEADR_GH_TOKEN }}
